# Generated by Django 6.0.4 on 2026-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la formation')),
                ('details', models.TextField(verbose_name='Détails de la formation')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('challenge', models.TextField(verbose_name='Enjeu / Défi')),
                ('result', models.TextField(verbose_name='Résultat')),
                ('stack', models.CharField(max_length=250, verbose_name='Technologies utilisées')),
                ('image_url', models.URLField(blank=True, help_text="Lien vers l'image (ex: /assets/Gnosis.PNG ou lien web)", null=True, verbose_name="URL de l'image")),
            ],
        ),
    ]
