# Generated by Django 6.0.4 on 2026-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formation_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre (ex: Notre Mission)')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_name', models.CharField(help_text='Ex: Target, Eye, Heart', max_length=50, verbose_name="Nom de l'icône (lucide-react)")),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image de fond")),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('service', models.CharField(max_length=100, verbose_name='Service souhaité')),
                ('message', models.TextField(verbose_name='Détails du projet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
