# Generated by Django 6.0.4 on 2026-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companyvalue_quoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvalue',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Image de fond'),
        ),
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/', verbose_name='Image de la formation'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image du projet'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo de profil'),
        ),
    ]
