# Generated by Django 6.0.4 on 2026-04-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_heroslide_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_projects', models.IntegerField(default=0, verbose_name='Projets accompagnés')),
                ('stats_sectors', models.IntegerField(default=0, verbose_name='Secteurs couverts')),
                ('stats_satisfaction', models.IntegerField(default=100, verbose_name='Pourcentage de clients satisfaits')),
                ('address', models.CharField(default='Kabondo Avenue Lac Rweru No7', max_length=200)),
                ('email', models.EmailField(default='info@innotech.bi', max_length=254)),
                ('phone', models.CharField(default='+257 000 000', max_length=50)),
            ],
            options={
                'verbose_name': "Information de l'entreprise",
                'verbose_name_plural': "Informations de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name="Email de l'abonné")),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
