# Generated by Django 6.0.4 on 2026-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_companyinfo_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Innovation For The Future', max_length=200)),
                ('description', models.TextField(default='Innotech Impact empowers businesses through modern technology, innovation and digital solutions.')),
                ('button_text', models.CharField(default='Discover More', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Image de fond')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Vidéo de présentation')),
            ],
            options={
                'verbose_name': 'Section Background',
                'verbose_name_plural': 'Sections Background',
            },
        ),
    ]
