# Generated by Django 6.0.4 on 2026-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_backgroundsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_description',
            field=models.TextField(default="Innotech Impact est une entreprise technologique pionnière qui s'engage à transformer le paysage numérique...", verbose_name='Texte À Propos'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image À Propos'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_title',
            field=models.CharField(default='QUI SOMMES-NOUS?', max_length=200, verbose_name='Titre À Propos'),
        ),
    ]
