# Generated by Django 6.0.3 on 2026-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_companyinfo_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role', models.CharField(max_length=100, verbose_name='Poste / Rôle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie courte')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Lien Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Lien Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['created_at'],
            },
        ),
    ]
