# Generated by Django 6.0.3 on 2026-04-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='map_url',
            field=models.TextField(blank=True, help_text="Collez ici le lien src de l'iframe Google Maps", null=True, verbose_name='Lien Embed Google Maps'),
        ),
    ]
