# Generated by Django 6.0.4 on 2026-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_companyinfo_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'étape")),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Étape de collaboration',
                'verbose_name_plural': 'Étapes de collaboration',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='description',
            field=models.TextField(default='Innotech Impact empowers businesses through modern technology...'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_description',
            field=models.TextField(default='Innotech Impact est une entreprise technologique pionnière...', verbose_name='Texte À Propos'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='stats_satisfaction',
            field=models.IntegerField(default=100, verbose_name='% de clients satisfaits'),
        ),
    ]
